var_semana = ["lunes", "miércoles", "jueves", "viernes", "sábado", "enero"]
var_semana.append("domingo")
var_semana.insert(1, "martes")
var_semana.pop(6)
print(var_semana)
lunes=var_semana.index("lunes")
martes=var_semana.index("martes")
miercoles=var_semana.index("miércoles")
jueves=var_semana.index("jueves")
viernes=var_semana.index("viernes")
sabado=var_semana.index("sábado")
domingo=var_semana.index("domingo")
print(f"lunes está en la posición {lunes}")
print(f"martes está en la posición {martes}")
print(f"miercoles está en la posición {miercoles}")
print(f"jueves está en la posición {jueves}")
print(f"viernes está en la posición {viernes}")
print(f"sábado está en la posición {sabado}")
print(f"domingo está en la posición {domingo}")